### ISSUE TITLE
[FlowExplorer] Search by Timestamp/flowid/direction did not return result

### ISSUE THREAD

**Issue by minimilk** [nuagenetworks/visualization-framework#516]
Tried _4cc02db3_:
1. Search by Timestamp/flowid/direction did not return result
2. Search by subnet returns result though.

![direction](https://user-images.githubusercontent.com/9605878/32975944-17f429d0-cbc2-11e7-8b3c-92605ca31a9c.png)
![flowid](https://user-images.githubusercontent.com/9605878/32975945-180bbfc8-cbc2-11e7-9284-a11499be5fdf.png)
![search-by-dmac](https://user-images.githubusercontent.com/9605878/32975946-18273618-cbc2-11e7-972c-8fa7272d7a2f.png)
![search-by-timestamp](https://user-images.githubusercontent.com/9605878/32975947-184004d6-cbc2-11e7-9f6f-c83b05fb6ba0.png)
![successful-search](https://user-images.githubusercontent.com/9605878/32975948-185b6af0-cbc2-11e7-8ec2-1b11d0d1e5dd.png)

**Comment by nxanil** [comment]
@minimilk @ronakmshah 
Search by Timestamp/flowid/direction did not return result:
Since **flowid** and **direction** columns are not present in the table so we can't search a data which is not displayed in a table view, and I believe if a user doesn't see the field on the table, then he will not search for such columns. Thoughts?

For **Timestamp**, the search should be made on formatted timestamp as displayed in table like:-
`Timestamp ==  "Nov 21, 17 4:41:04 PM"`

**Comment by minimilk** [comment]
So if I understand correctly, search by Timestamp should type exact string otherwise we won't get any result. IMO time search supposed to under given range instead of string match.

It seem the remaining part is for design team to make our feature more user friendly and intuitive.

**Comment by minimilk** [comment]
Close this issue as it is not an issue to be discussed here.
